### ISSUE TITLE
Corrupt message error when trying to connect with `STARTTLS`

### ISSUE THREAD

**Issue by danteissaias** [EC-Nordbund/denomailer#21]
## Describe the bug

Corrupt message error when trying to connect to https://ethereal.email on port `587` with `STARTTLS`.
```
error: Uncaught (in promise) InvalidData: received corrupt message
      const rr = await this.#rd.read(this.#buf.subarray(this.#w));
                 ^
    at async read (deno:ext/net/01_net.js:28:19)
    at async BufReader.#fill (https://deno.land/std@0.130.0/io/buffer.ts:323:18)
    at async BufReader.readSlice (https://deno.land/std@0.130.0/io/buffer.ts:609:9)
    at async BufReader.readLine (https://deno.land/std@0.130.0/io/buffer.ts:497:14)
    at async TextProtoReader.readLineSlice (https://deno.land/std@0.130.0/textproto/mod.ts:131:11)
    at async TextProtoReader.readLine (https://deno.land/std@0.130.0/textproto/mod.ts:33:15)
    at async SMTPConnection.readCmd (https://deno.land/x/denomailer@1.0.1/client/basic/connection.ts:76:19)
    at async SMTPClient.#prepareConnection (https://deno.land/x/denomailer@1.0.1/client/basic/client.ts:302:7)
    at async https://deno.land/x/denomailer@1.0.1/client/basic/client.ts:55:7
```

## Code example

```typescript
import { SMTPClient } from "https://deno.land/x/denomailer@1.0.1/mod.ts";

const auth = {
  username: /* redacted */,
  password:  /* redacted */,
};

export const email = new SMTPClient({
  connection: {
    hostname: "smtp.ethereal.email",
    port: 587,
    tls: true,
    auth,
  },
});
```

## Logs

```
deno 1.21.1 (release, aarch64-apple-darwin)
v8 10.0.139.17
typescript 4.6.2
```

**Comment by danteissaias** [comment]
Thanks.

**Comment by mathe42** [comment]
No problem!
